version: 2.1

orbs:
  fortify: signavio/fortify@2.0.0
  blackduck: signavio/blackduck@1.11.0
references:
  workspace_root: &workspace_root ~/project
executors:
  fortify:
    machine:
      image: ubuntu-2004:202201-02
    resource_class: 2xlarge

aliases:
  - &onlyMaster
    filters:
      branches:
        only:
          - master
          
jobs:
  build:
    docker:
      - image: mozilla/sbt:11.0.8_1.3.13
    steps:
      - checkout
      - run:
          name: Test
          command: |
            # sbt "project core" test:test
            # sbt "project math" test:test
            # sbt "project data" test:test
            # sbt "project graph" test:test
      - run:
          name: build artifacts
          command: |
            sbt "project core" package
            sbt "project math" package
            sbt "project data" package
            sbt "project graph" package
      - run:
          name: collect jar artifacts
          command: |
            mkdir -p jars
            mv core/target/*.jar jars
            mv math/target/*.jar jars
            mv data/target/*.jar jars
            mv graph/target/*.jar jars
      - store_artifacts:
          path: jars

  fortify-translate-and-scan:
    executor: fortify
    steps:
      - checkout
      - fortify/setup
      - run:
          name: 'Fortify: translate '
          command: |
            sourceanalyzer -b smile -verbose \
              core/src/main math/src/main data/src/main graph/src/main
      - run:
          name: 'Fortify: scan'
          command: |
            sourceanalyzer -b smile -verbose -scan -f smile.fpr
      - store_artifacts:
          path: smile.fpr
      - run:
          name: 'Fortify: upload'
          command: |
            fortifyclient \
               -url "$FORTIFY_SSC" \
               -authtoken "$SSC_API_TOKEN" \
               uploadFPR \
               -file smile.fpr \
               -project signavio-smile \
               -version master

  blackduck-scan:
    working_directory: *workspace_root
    machine:
      image: ubuntu-2004:202010-01
    resource_class: large
    environment:
      BLACKDUCK_PROJECT_GROUP: SAP_Signavio_Process_Intelligence
    steps:
      - checkout
      - run:
          name: Compile Core
          command: |
            sbt core/compile
      - blackduck/blackduck-detect:
          blackduck-project-group: $BLACKDUCK_PROJECT_GROUP
          blackduck-project-name: smile
          blackduck-project-path: /home/circleci/project/core
      - run:
          name: Compile Math
          command: |
            sbt math/compile
      - blackduck/blackduck-detect:
          blackduck-project-group: $BLACKDUCK_PROJECT_GROUP
          blackduck-project-name: smile
          blackduck-project-path: /home/circleci/project/math
      - run:
          name: Compile Data
          command: |
            sbt data/compile
      - blackduck/blackduck-detect:
          blackduck-project-group: $BLACKDUCK_PROJECT_GROUP
          blackduck-project-name: smile
          blackduck-project-path: /home/circleci/project/data
      - run:
          name: Compile Graph
          command: |
            sbt graph/compile
      - blackduck/blackduck-detect:
          blackduck-project-group: $BLACKDUCK_PROJECT_GROUP
          blackduck-project-name: smile
          blackduck-project-path: /home/circleci/project/graph

workflows:
  build-and-deploy:
    jobs:
      - build:
          context: ECR
          
  fortify-workflow:
    triggers:
      - schedule:
          cron: "30 2 * * 0"
          <<: *onlyMaster
    jobs:
      - fortify-translate-and-scan:
          context:
            - fortify

  blackduck-nightly-scan:
    triggers:
      - schedule:
          cron: "30 2 * * *" # UTC
          <<: *onlyMaster
    jobs:
      - blackduck-scan:
          context:
            - ECR
            - BlackDuck


