version: 2.1

orbs:
  fortify: signavio/fortify@2.0.0

executors:
  fortify:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: 2xlarge

aliases:
  - &onlyMaster
    filters:
      branches:
        only:
          - master
          
jobs:
  build:
    docker:
      - image: mozilla/sbt:11.0.8_1.3.13
    steps:
      - checkout
      - run:
          name: Test
          command: |
            # sbt "project core" test:test
            # sbt "project math" test:test
            # sbt "project data" test:test
            # sbt "project graph" test:test
      - run:
          name: build artifacts
          command: |
            sbt "project core" package
            sbt "project math" package
            sbt "project data" package
            sbt "project graph" package
      - store_artifacts:
          path: core/target/*.jar
      - store_artifacts:
          path: math/target/*.jar
      - store_artifacts:
          path: data/target/*.jar
      - store_artifacts:
          path: graph/target/*.jar


  fortify-translate-and-scan:
    executor: fortify
    steps:
      - checkout
      - fortify/setup
      - run:
          name: 'Fortify: translate '
          command: |
            sourceanalyzer -b smile -verbose ./
      - run:
          name: 'Fortify: scan'
          command: |
            sourceanalyzer -b smile -verbose -scan -f smile.fpr
      - store_artifacts:
          path: smile.fpr

workflows:
  build-and-deploy:
    jobs:
      - build:
          context: ECR
          
  fortify-workflow:
  #  triggers:
  #    - schedule:
  #        cron: "30 2 * * 0"
  #        <<: *onlyMaster
    jobs:
      - fortify-translate-and-scan:
          context:
            - fortify
